apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-mind
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive-mind
  template:
    metadata:
      labels:
        app: hive-mind
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["hive-mind"]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: simulation-node
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "Kovan Zihni aktif. Cihaz ID: $(hostname). CPU Yuk: $(cat /proc/loadavg)";
              sleep 5;
            done
