apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-organism
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organism
  template:
    metadata:
      labels:
        app: organism
    spec:
      containers:
      - name: organism-container
        image: alpine:3.18
        # Paket yüklemeden, doğrudan kendi 'inek' mantığımızı oluşturuyoruz
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              LOAD=$(cat /proc/loadavg | cut -d' ' -f1);
              echo " ________________________________________ ";
              echo "< Pi'nin icindeki ruh: $(date +%H:%M:%S) >";
              echo "< CPU Yuk: $LOAD                   >";
              echo " ---------------------------------------- ";
              echo "        \   ^__^";
              echo "         \  (oo)\_______";
              echo "            (__)\       )\\/\\";
              echo "                ||----w |";
              echo "                ||     ||";
              sleep 10;
            done
