apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-organism
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organism
  template:
    metadata:
      labels:
        app: organism
    spec:
      containers:
      - name: organism-container
        image: alpine:3.18
        # Önce paketleri yükle, sonra sonsuz döngüde inek konuşsun
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache cowsay;
            while true; do
              cowsay "Pi'nin icindeki ruh: $(date +%H:%M:%S) - CPU Yuk: $(cat /proc/loadavg | cut -d' ' -f1)";
              sleep 10;
            done
---
apiVersion: v1
kind: Service
metadata:
  name: organism-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: organism
  ports:
  - port: 80
    targetPort: 80
