apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-organism
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organism  # Burası 'jellyfin' değil, 'organism' olmalı!
  template:
    metadata:
      labels:
        app: organism # Burası da 'organism' olmalı
    spec:
      containers:
      - name: cowsay-service
        image: docker.io/library/alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["apk add --no-cache cowsay && while true; do cowsay 'Benim Raspberry Pi artik yasiyor... Ve su anki sayi: '$(date +%S); sleep 5; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: organism-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: organism # Burası da 'organism' olmalı, Jellyfin'i karıştırmasın
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # Jellyfin 30096 kullanıyor, bu 30080. Çakışma olmaz.
