apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ollama-cluster
  namespace: default
spec:
  selector:
    matchLabels:
      app: ollama-node
  template:
    metadata:
      labels:
        app: ollama-node
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          hostPort: 11434
        resources:
          limits:
            cpu: "2"      # Maksimum 2 çekirdeğe kadar genişleyebilsin
            memory: 1.5Gi # RAM limitini de Pi'leri rahatlatmak için biraz kıstık
          requests:
            cpu: "0.2"    # İŞTE SİHİRLİ DOKUNUŞ: Başlangıçta sadece 0.2 çekirdek rezerve etsin (K3s yer bulabilsin)
            memory: 500Mi
