apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ollama-cluster
  namespace: default
spec:
  selector:
    matchLabels:
      app: ollama-node
  template:
    metadata:
      labels:
        app: ollama-node
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          hostPort: 11434
        resources:
          limits:
            cpu: "3"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
